-- =========================
-- RESET DATABASE (SAFE RE-RUN)
-- =========================
DROP TABLE IF EXISTS public.inventory;
DROP TABLE IF EXISTS public.account;
DROP TABLE IF EXISTS public.classification;
DROP TYPE IF EXISTS public.account_type;

-- =========================
-- CREATE TYPE
-- =========================
CREATE TYPE public.account_type AS ENUM
('Client', 'Employee', 'Admin');

-- =========================
-- TABLE: classification
-- =========================
CREATE TABLE IF NOT EXISTS public.classification (
  classification_id INT GENERATED BY DEFAULT AS IDENTITY,
  classification_name CHARACTER VARYING NOT NULL,
  CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- =========================
-- TABLE: inventory
-- =========================
CREATE TABLE IF NOT EXISTS public.inventory (
  inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  inv_make character varying NOT NULL,
  inv_model character varying NOT NULL,
  inv_year character(4) NOT NULL,
  inv_description text NOT NULL,
  inv_image character varying NOT NULL,
  inv_thumbnail character varying NOT NULL,
  inv_price numeric(9, 0) NOT NULL,
  inv_miles integer NOT NULL,
  inv_color character varying NOT NULL,
  classification_id integer NOT NULL,
  CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

ALTER TABLE public.inventory
  ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
  REFERENCES public.classification (classification_id)
  ON UPDATE CASCADE
  ON DELETE NO ACTION;

-- =========================
-- TABLE: account
-- =========================
CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client',
    CONSTRAINT account_pkey PRIMARY KEY (account_id),
    CONSTRAINT account_email_unique UNIQUE (account_email)
);

-- =========================
-- INSERT: classification
-- =========================
INSERT INTO public.classification (classification_name)
VALUES 
('Custom'),
('Sport'),
('SUV'),
('Truck'),
('Sedan');

-- =========================
-- INSERT: inventory
-- =========================
INSERT INTO public.inventory (
    inv_make, inv_model, inv_year, inv_description,
    inv_image, inv_thumbnail, inv_price,
    inv_miles, inv_color, classification_id
)
VALUES
('Chevy','Camaro','2018','If you want to look cool this is the car you need! This car has great performance at an affordable price. Own it today!','/images/camaro.jpg','/images/camaro-tn.jpg',25000,101222,'Silver',2),
('Batmobile','Custom','2007','Ever want to be a super hero? Now you can with the Batmobile.','/images/batmobile.jpg','/images/batmobile-tn.jpg',65000,29887,'Black',1),
('FBI','Surveillance Van','2016','Feel like a detective with this van.','/images/survan.jpg','/images/survan-tn.jpg',20000,19851,'Brown',1),
('Dog','Car','1997','Fun novelty car with a dog theme.','/images/dog-car.jpg','/images/dog-car-tn.jpg',35000,71632,'White',1),
('Jeep','Wrangler','2019','Perfect for off-road adventures.','/images/wrangler.jpg','/images/wrangler-tn.jpg',28045,41205,'Yellow',3),
('Lamborghini','Adventador','2016','High-performance sports car.','/images/adventador.jpg','/images/adventador-tn.jpg',417650,71003,'Blue',2),
('Aerocar International','Aerocar','1963','Car that converts into an airplane.','/images/aerocar.jpg','/images/aerocar-tn.jpg',700000,18956,'Red',1),
('Monster','Truck','1995','Huge tires and powerful engine.','/images/monster-truck.jpg','/images/monster-truck-tn.jpg',150000,3998,'Purple',1),
('Cadillac','Escalade','2019','Luxury SUV with premium features.','/images/escalade.jpg','/images/escalade-tn.jpg',75195,41958,'Black',4),
('GM','Hummer','2016','Rugged off-road vehicle.','/images/hummer.jpg','/images/hummer-tn.jpg',58800,56564,'Yellow',4),
('Mechanic','Special','1964','Project car for enthusiasts.','/images/mechanic.jpg','/images/mechanic-tn.jpg',100,200125,'Rust',5),
('Ford','Model T','1921','Historic classic vehicle.','/images/model-t.jpg','/images/model-t-tn.jpg',30000,26357,'Black',5),
('Mystery','Machine','1999','Famous mystery-solving van.','/images/mystery-van.jpg','/images/mystery-van-tn.jpg',10000,128564,'Green',1),
('Spartan','Fire Truck','2012','Fully equipped fire truck.','/images/fire-truck.jpg','/images/fire-truck-tn.jpg',50000,38522,'Red',4),
('Ford','Crown Victoria','2013','Former police vehicle.','/images/crwn-vic.jpg','/images/crwn-vic-tn.jpg',10000,108247,'White',5);
